name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-build
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Build and Install
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make uninstall
        make install

  Tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-tests
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Build and Install
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make uninstall
          make install

      - name: Run tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test
