name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cli/gh-extension-precompile@v2
        with:
          go_version_file: go.mod

  ReleaseTest:
    needs: Release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.os }}-rt
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - run: |
          gh extension install thombashi/gh-git-describe
          gh git-describe --log-level=debug da4fb9793585989a3d7723b4736ef157c632e2a2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
