name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cli/gh-extension-precompile@v2
        with:
          # cannot use version 1.22 until the issue https://github.com/cli/gh-extension-precompile/issues/50 is resolved.
          go_version: "1.21"
